// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTMepCQF8vBYD_-jEb4Mv01mi_nCBxClE',
    appId: '1:740975783088:web:919832c0d355fc4bb1df75',
    messagingSenderId: '740975783088',
    projectId: 'bidwise-34699',
    authDomain: 'bidwise-34699.firebaseapp.com',
    storageBucket: 'bidwise-34699.appspot.com',
    measurementId: 'G-S5NT0L2TV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Mop1yPtXyUGLmSmlmySsKMBfmEppp3Y',
    appId: '1:740975783088:android:bde29f1f1ede9d46b1df75',
    messagingSenderId: '740975783088',
    projectId: 'bidwise-34699',
    storageBucket: 'bidwise-34699.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWPrtUMg9rQMPxtTIsjXBfvFfFDbMys5w',
    appId: '1:740975783088:ios:33ad203365c53175b1df75',
    messagingSenderId: '740975783088',
    projectId: 'bidwise-34699',
    storageBucket: 'bidwise-34699.appspot.com',
    iosBundleId: 'com.example.bidwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWPrtUMg9rQMPxtTIsjXBfvFfFDbMys5w',
    appId: '1:740975783088:ios:3575b2faae9e90b4b1df75',
    messagingSenderId: '740975783088',
    projectId: 'bidwise-34699',
    storageBucket: 'bidwise-34699.appspot.com',
    iosBundleId: 'com.example.bidwise.RunnerTests',
  );
}
